### ISSUE TITLE
Provider is not working with latest koop version 4.X

### ISSUE THREAD

**Issue by sjain227** [koopjs/koop-provider-elasticsearch#15]
I have just updated koop with it's latest version 4.0.3 and found that Elastic search provider is throwing error - {"error":"features.forEach is not a function"}
Anything needs to be updated in elastic search model?

**Comment by keithfraley** [comment]
Is most like the es node client.  What once was response.hits.hits is now
response.body.hiits.hits

**Comment by sjain227** [comment]
@keithfraley I have not updated ES version, hence res.hits.hits is working fine for me, I noticed one strange thing that when we hit service for the first time, it returns the results correctly then onwards it starts throwing error. It does not even call getData function second time on. I see getData is now bound function, Could that be an issue?

**Comment by rgwozdz** [comment]
@sjain227 - this a bug in koop 4.x.; patch coming shortly

**Comment by rgwozdz** [comment]
@sjain227 - please try with Koop ^4.0.4

**Comment by sjain227** [comment]
@rgwozdz  Thanks a lot Rich for the patch, it works fine with Koop 4.0.4
